# Generated by Django 3.2.4 on 2021-06-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0002_auto_20210609_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='user_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
