# Generated by Django 3.2.4 on 2021-06-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0004_alter_registration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='user_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
