# Generated by Django 3.2.4 on 2021-06-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0006_auto_20210609_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='user_type',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
