# Generated by Django 3.2.4 on 2021-06-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0008_alter_registration_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='user_type',
        ),
    ]
