# Generated by Django 3.2.4 on 2021-06-10 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0012_taskassign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassign',
            name='login_user',
        ),
    ]
