# Generated by Django 3.2.4 on 2021-06-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0013_remove_taskassign_login_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskassign',
            old_name='employee_id',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='taskassign',
            name='reason',
        ),
    ]
