# Generated by Django 3.2.4 on 2021-06-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0014_auto_20210610_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='dup_password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
