# Generated by Django 3.2.4 on 2021-06-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0015_labour_dup_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labour',
            name='dup_password',
        ),
    ]
