# Generated by Django 3.2.4 on 2021-06-10 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0016_remove_labour_dup_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassign',
            name='labour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_admin.labour'),
            preserve_default=False,
        ),
    ]
