# Generated by Django 3.2.4 on 2021-06-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0017_taskassign_labour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskassign',
            old_name='task',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='taskassign',
            name='day_status',
        ),
        migrations.RemoveField(
            model_name='taskassign',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='taskassign',
            name='request_status',
        ),
        migrations.RemoveField(
            model_name='taskassign',
            name='status',
        ),
        migrations.RemoveField(
            model_name='taskassign',
            name='to_date',
        ),
    ]
