# Generated by Django 3.2.4 on 2021-06-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0018_auto_20210610_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassign',
            name='labour',
        ),
        migrations.AddField(
            model_name='taskassign',
            name='labour_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
