# Generated by Django 3.2.4 on 2021-06-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0019_auto_20210610_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassign',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
