# Generated by Django 3.2.4 on 2021-06-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0020_taskassign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='user_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.IntegerField(default=None),
        ),
    ]
