# Generated by Django 3.2.4 on 2021-06-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0021_auto_20210610_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
