# Generated by Django 3.2.4 on 2021-06-11 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0022_alter_registration_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_id', models.CharField(blank=True, max_length=255, null=True)),
                ('complaint', models.CharField(blank=True, max_length=255, null=True)),
                ('day_status', models.CharField(default='full', max_length=255)),
                ('request_status', models.CharField(default='pending', max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('login_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_admin.labour')),
            ],
        ),
    ]
