# Generated by Django 3.2.4 on 2021-06-11 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0024_remove_ticket_login_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='login_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_admin.registration'),
            preserve_default=False,
        ),
    ]
