# Generated by Django 3.2.4 on 2021-06-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0025_ticket_login_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='login_user',
        ),
    ]
