# Generated by Django 3.2.4 on 2021-06-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0026_remove_ticket_login_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
