# Generated by Django 3.2.5 on 2021-07-19 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0030_defaultfiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labour',
            new_name='user',
        ),
    ]
