# Generated by Django 3.2.5 on 2021-07-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0031_rename_labour_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Labour',
        ),
    ]
