# Generated by Django 3.2.7 on 2021-09-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0032_rename_user_labour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='complaint',
            new_name='leave',
        ),
    ]
