# Generated by Django 3.2.7 on 2021-09-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0033_rename_complaint_ticket_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
