# Generated by Django 3.2.7 on 2021-09-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0034_labour_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='leavee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
