# Generated by Django 2.2.12 on 2021-09-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0036_auto_20210928_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
