# Generated by Django 2.2.12 on 2021-09-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0037_ticket_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='leave',
        ),
    ]
