# Generated by Django 3.2.7 on 2021-10-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0039_auto_20211005_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labour',
            old_name='company_name',
            new_name='company_info',
        ),
    ]
