# Generated by Django 3.2.7 on 2021-10-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0040_rename_company_name_labour_company_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labour',
            old_name='company_info',
            new_name='company_name',
        ),
    ]
