# Generated by Django 3.0.7 on 2021-10-07 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0041_rename_company_info_labour_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('email', models.TextField(blank=True, default='', null=True)),
                ('phone', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_admin.Client')),
            ],
        ),
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='defaultfiles',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taskassign',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.TextField(blank=True, default='', null=True)),
                ('field2', models.TextField(blank=True, default='', null=True)),
                ('field3', models.TextField(blank=True, default='', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_admin.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.TextField(blank=True, default='', null=True)),
                ('field2', models.TextField(blank=True, default='', null=True)),
                ('field3', models.TextField(blank=True, default='', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_admin.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Roof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.TextField(blank=True, default='', null=True)),
                ('field2', models.TextField(blank=True, default='', null=True)),
                ('field3', models.TextField(blank=True, default='', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_admin.Project')),
            ],
        ),
    ]
