# Generated by Django 3.2.8 on 2021-10-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0043_auto_20211010_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='namee',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
