# Generated by Django 3.2.8 on 2021-10-09 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0044_client_namee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='namee',
        ),
    ]
