# Generated by Django 3.2.5 on 2021-10-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0047_auto_20211010_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(max_length=50),
        ),
    ]
