# Generated by Django 3.2.5 on 2021-10-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0049_alter_client_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
