# Generated by Django 3.2.5 on 2021-10-10 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0052_auto_20211010_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='roof',
            name='client_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_admin.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roof',
            name='field1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roof',
            name='field2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roof',
            name='field3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roof',
            name='project',
            field=models.CharField(max_length=200),
        ),
    ]
