# Generated by Django 3.2.5 on 2021-10-11 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0053_auto_20211010_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roof',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_admin.client'),
        ),
    ]
