# Generated by Django 3.2.8 on 2021-10-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0056_auto_20211011_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='roof',
            name='images',
            field=models.ImageField(default=1, upload_to='', verbose_name='image/'),
            preserve_default=False,
        ),
    ]
