# Generated by Django 3.2.8 on 2021-10-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0057_roof_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roof',
            name='images',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
