# Generated by Django 3.2.8 on 2021-10-11 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0058_alter_roof_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='field1',
            new_name='create_room',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='field2',
            new_name='equipments',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='field3',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='project',
        ),
        migrations.AddField(
            model_name='room',
            name='client_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_admin.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.ImageField(default=1, upload_to='room_img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='wattage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='roof',
            name='images',
            field=models.ImageField(upload_to='roof_img/'),
        ),
    ]
