# Generated by Django 3.2.8 on 2021-10-11 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0059_auto_20211011_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fount_of_building', models.ImageField(upload_to='images_api/front_building/')),
                ('array', models.ImageField(upload_to='images_api/array/')),
                ('meter_close_up', models.ImageField(upload_to='images_api/meter_close_up/')),
                ('proposed_disconnected_location', models.ImageField(upload_to='images_api/proposed/')),
                ('south_house', models.ImageField(upload_to='images_api/south_house')),
                ('south_yard', models.ImageField(upload_to='images_api/south_yard')),
                ('electrical_panel_location', models.ImageField(upload_to='images_api/electrical_panel')),
                ('electrical_panel_circute_breakers', models.ImageField(upload_to='images_api/electrical_panel_breakes')),
                ('roof_pitch_proposed_inverter_and_bank_location', models.ImageField(upload_to='images_api/roof_pitch')),
                ('proposed_efficiency_upgrade_location', models.ImageField(upload_to='images_api/proposed_effiency')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_admin.client')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roof',
            name='images',
            field=models.ImageField(upload_to='images_api/roof_img/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='images',
            field=models.ImageField(upload_to='images_api/room_img/'),
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
