# Generated by Django 3.2.8 on 2021-10-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0060_auto_20211011_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_id',
        ),
        migrations.AddField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
