# Generated by Django 3.2.8 on 2021-10-11 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0061_auto_20211011_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Equipments_and_working_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inverter_mounting_type', models.CharField(blank=True, max_length=200, null=True)),
                ('ventilated_room', models.CharField(blank=True, max_length=200, null=True)),
                ('dc_cable_run_in_m', models.CharField(blank=True, max_length=200, null=True)),
                ('building_CAD_drawings_available', models.CharField(blank=True, max_length=200, null=True)),
                ('building_electrical_drawings_available', models.CharField(blank=True, max_length=200, null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_admin.client')),
            ],
        ),
    ]
