# Generated by Django 3.2.8 on 2021-10-11 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0062_add_equipments_and_working_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Electrical_connection_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Electricity_provider', models.CharField(blank=True, max_length=200, null=True)),
                ('sc_no', models.CharField(blank=True, max_length=200, null=True)),
                ('capture_connection_no', models.ImageField(upload_to='images_api/connection_no/')),
                ('previous_monthly_bills_copy', models.ImageField(upload_to='images_api/mothly_bills/')),
                ('service', models.CharField(max_length=200)),
                ('other_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('voltage', models.CharField(max_length=100)),
                ('phase', models.CharField(max_length=150)),
                ('available_breaker_space', models.CharField(max_length=200)),
                ('capture_breaker_space_image', models.ImageField(upload_to='images_api/breaker_space_image/')),
                ('Separate_electrical_room_available', models.CharField(max_length=100)),
                ('capture_electrical_room', models.ImageField(upload_to='images_api/capture_electrical_room/')),
                ('cable_routing', models.CharField(max_length=100)),
                ('capture_connection_number', models.ImageField(upload_to='images/api/capture_connection_no/')),
                ('roof_to_electrical_room_cable_length_in_m', models.CharField(max_length=255)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_admin.client')),
            ],
        ),
    ]
