# Generated by Django 3.2.8 on 2021-10-11 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0063_add_electrical_connection_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Backup_Generator_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_backup_generate_available', models.CharField(blank=True, max_length=155, null=True)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity_in_KVA', models.CharField(blank=True, max_length=255, null=True)),
                ('electrical_phase', models.CharField(blank=True, max_length=155, null=True)),
                ('auto_start_option_available', models.CharField(blank=True, max_length=155, null=True)),
                ('daily_operations_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('change_over_switch_rating', models.CharField(blank=True, max_length=255, null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_admin.client')),
            ],
        ),
    ]
