# Generated by Django 3.2.8 on 2021-10-11 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0064_add_backup_generator_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miscellaneous_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earthing_pit_visibility', models.CharField(max_length=155)),
                ('easy_access_to_roof', models.CharField(blank=True, max_length=155, null=True)),
                ('need_of_scaffoiding_during_installation', models.CharField(blank=True, max_length=200, null=True)),
                ('available_of_wedding_facility_in_site', models.CharField(blank=True, max_length=200, null=True)),
                ('availability_of_crane_service', models.CharField(blank=True, max_length=200, null=True)),
                ('availability_of_ladder_facility', models.CharField(blank=True, max_length=200, null=True)),
                ('availability_of_building_electricion', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_admin.client')),
            ],
        ),
    ]
