# Generated by Django 3.0.7 on 2021-10-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0069_auto_20211012_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_electrical_connection_details',
            name='project_name',
        ),
    ]
