# Generated by Django 3.0.7 on 2021-10-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0070_remove_add_electrical_connection_details_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
    ]
