# Generated by Django 3.0.7 on 2021-10-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0071_registration_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
